openapi: 3.0.3
info:
  title: Reminder API
  description: Task reminder endpoints for AI-Powered Todo Chatbot
  version: 1.0.0

paths:
  /api/tasks/{task_id}/reminders:
    parameters:
      - name: task_id
        in: path
        required: true
        description: Task UUID
        schema:
          type: string
          format: uuid

    post:
      summary: Create a reminder for a task
      description: Schedule a reminder for the specified task
      operationId: createReminder
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReminderCreate'
      responses:
        '201':
          description: Reminder created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReminderResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          $ref: '#/components/responses/ValidationError'

    get:
      summary: List reminders for a task
      description: Get all reminders for the specified task
      operationId: listTaskReminders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of reminders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReminderListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/reminders/{reminder_id}:
    parameters:
      - name: reminder_id
        in: path
        required: true
        description: Reminder UUID
        schema:
          type: string
          format: uuid

    get:
      summary: Get a specific reminder
      description: Get reminder details by ID
      operationId: getReminder
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reminder details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReminderResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a reminder
      description: Remove a scheduled reminder
      operationId: deleteReminder
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Reminder deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ReminderCreate:
      type: object
      required:
        - remind_at
      properties:
        remind_at:
          type: string
          format: date-time
          description: When to send the reminder
          example: "2025-02-10T09:00:00Z"

    ReminderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        task_id:
          type: string
          format: uuid
        user_id:
          type: string
        remind_at:
          type: string
          format: date-time
        is_sent:
          type: boolean
        sent_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time

    ReminderListResponse:
      type: object
      properties:
        reminders:
          type: array
          items:
            $ref: '#/components/schemas/ReminderResponse'
        total:
          type: integer

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
