apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: task-events
  routes:
    default: /events/task-events
  scopes:
    - backend
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminders-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: reminders
  routes:
    default: /events/reminders
  scopes:
    - backend
    - notification-consumer
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-updates-subscription
  namespace: todo-app
spec:
  pubsubname: kafka-pubsub
  topic: task-updates
  routes:
    default: /events/task-updates
  scopes:
    - backend
